module.exports = ["Enjoy at least one sunset per day! – Modern Family"
, "They say don’t try this at home…so I went to my friends home!"
, "My bed is a magical place I suddenly remember everything I had to do."
, "Friday, my second favorite F word."
, "Wine + dinner = winner"
, "I don’t care what people think of me. Mosquitos find me attractive!"
, "Stomach: I will now demonstrate a blue whale’s mating call."
, "If there would be an award for being lazy, I would send someone to pick it up for me."
, "They say: Do what you love and the money will come to you. Just ordered pizza, now I am waiting…"
, "For me, math class is like watching a foreign movie without subtitles."
, "Maybe if we tell people the brain is an app, they will start using it."
, "When nothing goes right, go left."
, "A cop pulled me over and told me “Papers”, so I said “Scissors, I win!” and drove off."
, "Mom: Why is everything on the floor? Me: Gravity!"
, "Sure, I do marathons. On Netflix."
, "Did it for the memories – totally worth it!"
, "I followed a diet but it didn’t follow me back, so I unfollowed it."
, "When Jessica Biel becomes pregnant, I hope she names her child 'Mo'."
, "Dear sleep: thanks for trying, but you can’t beat surfing the net."
, "I don’t think inside the box and I don’t think outside the box… I don’t even know where the box is."
, "Do I run? Yes… Out of time, patients and money."
, "There’s no 'we' in fries"
, "Lies I tell myself: Just one more cookie. Just one more movie. Just one more minute. Yet…I wouldn’t call them lies!"
, "I like hashtags, because they look like waffles."
, "ETC. End of Thinking Capacity."
, "Be a cupcake in a world of muffins"
, "I know the voices in my head aren’t real….. but sometimes their ideas are just absolutely awesome!"
, "Today is a good day for cake."
, "Going to bed early. Not going to a party. Not leaving my house. My childhood punishments has become my adult goals."
];